//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapitalGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapitalGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkmark {
            get {
                object obj = ResourceManager.GetObject("checkmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amsterdam, Netherlands
        ///Andorra la Vella, Andorra
        ///Athens, Greece
        ///Belgrade, Serbia
        ///Berlin, Germany
        ///Bern, Switzerland
        ///Bratislava, Slovakia
        ///Brussels, Belgium
        ///Bucharest, Romania
        ///Budapest, Hungary
        ///Chisinau, Moldova
        ///Copenhagen, Denmark
        ///Dublin, Ireland
        ///Helsinki, Finland
        ///Kiev, Ukraine
        ///Lisbon, Portugal
        ///Ljubljana, Slovenia
        ///Luxembourg, Luxembourg
        ///Madrid, Spain
        ///Minsk, Belarus
        ///Monaco, Monaco
        ///Moscow, Russia
        ///Nicosia, Cyprus
        ///Nuuk, Greenland
        ///Oslo, Norway
        ///Paris, France
        ///Podgorica, Montenegro
        ///Prague,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montgomery, Alabama
        ///Helena, Montana
        ///Juneau, Alaska
        ///Lincoln, Nebraska
        ///Phoenix, Arizona
        ///Carson City, Nevada
        ///Little Rock, Arkansas
        ///Concord, New Hampshire
        ///Sacramento, California
        ///Trenton, New Jersey
        ///Denver, Colorado
        ///Santa Fe, New Mexico
        ///Hartford, Connecticut
        ///Albany, New York
        ///Dover, Delaware
        ///Raleigh, North Carolina
        ///Tallahassee, Florida
        ///Bismarck, North Dakota
        ///Atlanta, Georgia
        ///Columbus, Ohio
        ///Honolulu, Hawaii
        ///Oklahoma City, Oklahoma
        ///Boise, Idaho
        ///Salem, Oregon
        ///Springfield, Illinois
        ///Harrisburg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string states {
            get {
                return ResourceManager.GetString("states", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unitedStatesMap {
            get {
                object obj = ResourceManager.GetObject("unitedStatesMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrong {
            get {
                object obj = ResourceManager.GetObject("wrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
